apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-contract
spec:
  secretName: api-contract-tls
  dnsNames:
    - "dita-api-contract.hasankarimi.ir"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
