apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-contract
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dita-api-contract.hasankarimi.ir
      secretName: api-contract-tls
  rules:
    - host: dita-api-contract.hasankarimi.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-contract
                port:
                  name: http
