apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: backendd/dita.account:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP__LISTEN_ADDR
              value: "0.0.0.0:8080"
            - name: APP__KRATOS__ADMIN_URL
              value: "http://kratos.iam:4434"
            - name: APP__AUTH__PRINCIPAL_HEADER
              value: "X-Auth-Request-User"
            - name: RUST_LOG
              value: "info"
            # Immediately return unused memory pages to the OS.
            - name: MIMALLOC_PURGE_DELAY
              value: "0"
            # Disable Transparent Huge Pages to minimize memory footprint.
            - name: MIMALLOC_ALLOW_THP
              value: "0"
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 0m
              memory: 0Mi